apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: __AWS_REGION__
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: voting-app-db-secret
  namespace: default
spec:
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: voting-app-db-secret
  data:
    - secretKey: password
      remoteRef:
        key: __POSTGRES_SECRET_NAME__
        property: password
    - secretKey: username
      remoteRef:
        key: __POSTGRES_SECRET_NAME__
        property: username
