apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  labels:
    app: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - name: result
          image: __AWS_ACCOUNT_ID__.dkr.ecr.__AWS_REGION__.amazonaws.com/voting-app/result:__IMAGE_TAG__
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: voting-app-config
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: voting-app-db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: voting-app-db-secret
                  key: password

---
apiVersion: v1
kind: Service
metadata:
  name: result
spec:
  type: ClusterIP
  selector:
    app: result
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
